@startuml
title <size:24>Infrastructure</size>

set separator none
top to bottom direction

<style>
  root {
    BackgroundColor: #ffffff
    FontColor: #444444
  }
</style>

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

System_Boundary("ecommercemonolith_boundary", "ecommerce-monolith", $tags="") {
  Container_Boundary("ecommercemonolith.ecommercemonolith_boundary", "ecommerce-monolith", $tags="") {
    Component(ecommercemonolith.ecommercemonolith.Infrastructure, "Infrastructure", $techn="Module", $descr="", $tags="", $link="")
  }

}

SHOW_LEGEND(true)
hide stereotypes
@enduml